Back out "Move erlang_service to use unix domain socket for communication"
Summary:
Original commit changeset: 2f731138e2c5

Original Phabricator Diff: D55432862

Unfortunately, this seems to break the VS Code integration. If I open a project and start issuing requests during the initial parsing (e.g. by making a modification to a file and saving) the parsing breaks completely. The status bar gets stuck and the following is visible in the logs:

```
client exited without proper shutdown sequence
[Error - 1:33:48 AM] exited with code 101
[Info  - 1:33:49 AM] Language service erlang-elp@file:### has crashed and will be restarted!
```

```
[2024-03-28T01:34:59.100] [ERROR] nuclide-vscode-api - LSP stderr erlang-elp@file:###: thread 'main' panicked at crates/elp/src/server/progress.rs:164:47:
called Result::unwrap() on an Err value: "SendError(..)"
stack backtrace:
```

After a while, ELP is automatically restarted until the maximum number of attempts is reached. At that point it is killed.

Interestingly enough, no other useful information is present in the logs.

Reviewed By: sopotc

Differential Revision: D55468816

fbshipit-source-id: 2a3ec92fbfc97d46ecb2e1a970300215691e009a