Handle -file attribute in .erl files
Summary:
Before this change, `elp parse-elp` would crash on a module containing a file attribute, due to:

```
thread 'tests::parse_elp_file_attribute::rebar' panicked at /data/sandcastle/boxes/fbsource/fbcode/whatsapp/elp/meta/vendor/paths/src/lib.rs:79:36:
expected absolute path, got file_attribute.hrl
``

Reviewed By: alanz

Differential Revision: D57434668

fbshipit-source-id: e5f062b60fe245ba7456af9cade4dd26ade49805