BE: validate test fixture
Summary:
A common mistake when writing a declarative test fixture is to have a syntax error in it.

This diff adds `ChangeFixture::validate` to check for these, and panic if found, e.g.

```
thread 'tests::validate_fixture_with_parse_error' panicked at crates/ide_db/src/lib.rs:462:17:
Fixture validation failed: syntax errors found in test fixture

File: /src/test.erl
Errors: [Missing(")", 19..19)]
Content:
-module(test).
foo( -> ok.

Parse Tree:
SourceFile {
    syntax: SOURCE_FILE@0..27
      MODULE_ATTRIBUTE@0..14
        ANON_DASH@0..1 "-"
        ANON_MODULE@1..7 "module"
        ANON_LPAREN@7..8 "("
        ATOM@8..12
          ATOM@8..12 "test"
        ANON_RPAREN@12..13 ")"
        ANON_DOT@13..14 "."
      WHITESPACE@14..15 "\n"
      FUN_DECL@15..26
        FUNCTION_CLAUSE@15..25
          ATOM@15..18
            ATOM@15..18 "foo"
          EXPR_ARGS@18..19
            ANON_LPAREN@18..19 "("
          WHITESPACE@19..20 " "
          CLAUSE_BODY@20..25
            ANON_DASH_GT@20..22 "->"
            WHITESPACE@22..23 " "
            ATOM@23..25
              ATOM@23..25 "ok"
        ANON_DOT@25..26 "."
      WHITESPACE@26..27 "\n"
    ,
}
 ---
If this is expected, add `//- expect_parse_errors` to the start of the fixture
```

A subsequent diff will apply it to the code base

Reviewed By: TD5

Differential Revision: D88948352

fbshipit-source-id: 532275075bb338191594966bb3292986442cead6