Pin 2022 version for Windows
Summary:
Starting in September 2025, GitHub moved the `latest` Windows label from 2022 to 2025. See the [announcement](https://github.com/actions/runner-images/issues/12677). This is the most likely cause behind the error:

```
Error: Tried to map a target OS from env. variable 'ImageOS' (got win25), but failed. If you're using a self-hosted runner, you should set 'env': 'ImageOS': ... to one of the following: ['ubuntu22', 'ubuntu24', 'win19', 'win22', 'macos13', 'macos14', 'macos15']
```

While this could be, in turn, caused by an issue with the `erlef/setup-beam` action, for the time being pin the version to 2022.

Reviewed By: jcpetruzza

Differential Revision: D83565904

fbshipit-source-id: 3bf7b8d6839c320fd017faa1f4597525009d747e